name: ci

on:
  push:
    branches:
      - "main"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # each step has a name, a 'uses' action, with credentials, etc
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          # context is the arg passed to the build command, could be rel/abs path
          # remote git, tarball, or plaintext
          # piped plaintext or tarball using std input
          # local dir, like code .
          context: .
          file: ./Dockerfile
          # upload to the registry after building
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest